name: Test variables using repo environments
on:
  push:
    branches:
      - main

jobs:
  dev:
    environment: dev
    runs-on: ubuntu-latest
    env:
      PASS: ${{ secrets.USER_PASSWORD }}
    steps:
      - name: output username
        run: echo "${{ vars.USERNAME }}"
      - name: output password
        run: echo "${{ env.PASS }}"
      - name: Get code
        uses: actions/checkout@v3
  prod:
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - name: output username
        run: echo ${{ vars.USERNAME }}
      - name: Get code
        uses: actions/checkout@v3
