name: reusable deploy

on: 
  workflow_call:
    inputs:
      artifact-name:
        description: 'The name of the artifact to download'
        required: true
        type: string
        default: my-artifact
      environment:
        description: 'The environment to deploy to'
        required: false
        type: string
        default: dev
    secrets:
      secret1:
        description: 'The username to use for this job'
        required: false
    outputs:
      result:
        description: 'The results of the job'
        value: ${{ jobs.deploy.outputs.outcome }}}
      



jobs:
  deploy:
    outputs:
      outcome: ${{ steps.output.outputs.step-result }}
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: list files
        run: ls -la
      - name: output
        run: | 
          echo "Hello, world!"
          echo "I am reusable!"
      - name: do i see env secret?
        run: echo ${{ secrets.USER_PASSWORD }}
      - name: output environment name
        run: echo ${{ inputs.environment }}
      - name: set result output
        id: output
        run: echo "step-result=success" >> $GITHUB_OUTPUT
  